### ISSUE TITLE
TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, int given

### ISSUE THREAD

**Issue by parth391** [worksome/request-factories#13]
I am getting below error, after the new release.

    TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, int given

    /vendor/worksome/request-factories/src/Actions/UndotArrayKeys.php:50
    /vendor/worksome/request-factories/src/Actions/UndotArrayKeys.php:50
    /vendor/worksome/request-factories/src/Actions/UndotArrayKeys.php:30
    /vendor/worksome/request-factories/src/Actions/UndotArrayKeys.php:34
    /vendor/worksome/request-factories/src/Actions/UndotArrayKeys.php:25
    /vendor/worksome/request-factories/src/RequestFactory.php:76

**Comment by lukeraymonddowning** [comment]
Added a fix for this in #14. Will merge and tag in just a moment.

**Comment by lukeraymonddowning** [comment]
v2.0.1 is now tagged and released, resolving this issue 👍
