### ISSUE TITLE
Method App\Http\Requests\<folder>\StoreRequest::factory does not exist.

### ISSUE THREAD

**Issue by jjjrmy** [worksome/request-factories#38]
```php
class StoreRequest extends FormRequest
{
    public static string $factory = StoreRequestFactory::class;
```

**Comment by jjjrmy** [comment]
Can you provide more clear examples?
No matter what I try I can't get Factories in other folders or the actual `FormRequest::factory` to work.

**Comment by olivernybroe** [comment]
What version do you have installed? 👀

**Comment by jjjrmy** [comment]
let me try now, I was on 2.5. Had to upgrade to PHP 8.2

**Comment by jjjrmy** [comment]
```
Could not find [Database\Requests\Invoice\StoreRequestFactory].
Please specify a relevant RequestFactory FQCN using a public static $factory property on
[App\Http\Requests\Invoice\StoreRequest].
```

**App\Http\Requests\Invoice\StoreRequest.php**
```php
namespace App\Http\Requests\Invoice;

use Database\Requests\Invoice\StoreRequestFactory;

class StoreRequest extends FormRequest
{
    public bool $newCustomer = true;

    public static $factory = StoreRequestFactory::class;
```


**Database\Requests\Invoice\StoreRequestFactory.php**
```php
namespace Database\Requests\Invoice;

use Worksome\RequestFactories\RequestFactory;

class StoreRequestFactory extends RequestFactory
{
    public function definition(): array
    {
        return [
```

**request-factories.php**
```php
return [
    /**
     * The default path for request factories is 'tests/RequestFactories'.
     * Keep this value as `null` to use the default. If you'd rather
     * change the default location, you may override it here.
     */
    'path' => 'database/requests',

    /**
     * If your request factories are located somewhere other than the
     * default location, you should update the namespace to reflect
     * that to prevent bugs when locating factories from a request.
     */
    'namespace' => 'Database\\Requests',
];
```

**Comment by olivernybroe** [comment]
let me add in the person who mainly build this :)

ping @lukeraymonddowning

**Comment by SDIjeremy** [comment]
bump

**Comment by jjjrmy** [comment]
bump, still not working and completely unusable unless you are on 8.2 which is not possible for my current project.

**Comment by lukeraymonddowning** [comment]
@jjjrmy as far as the 8.2 part is concerned, I've just tagged v2.6.0 which adds support for L10 when using older versions of PHP.

**Comment by lukeraymonddowning** [comment]
Not had chance to look into the issue yet but it is on my todo list

**Comment by lukeraymonddowning** [comment]
@jjjrmy quick thought on this: have you added the relevant PSR-4 autoloading entry to your `composer.json` file for the namespace you've created here? Should look something like this:


```json
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Seeders\\": "database/seeders/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Requests\\": "database/requests/"
```

**Comment by jjjrmy** [comment]
> @jjjrmy as far as the 8.2 part is concerned, I've just tagged v2.6.0 which adds support for L10 when using older versions of PHP.

Thank you, I think this is very necessary! I will give it a try.



> @jjjrmy quick thought on this: have you added the relevant PSR-4 autoloading entry to your `composer.json` file for the namespace you've created here?

I haven't revisited this, but I will try again with the v2.6.0

**Comment by lukeraymonddowning** [comment]
Going to close this as I haven't heard anything new 👍
